[build]
  command = "npm run prebuild && npm run build"
  functions = "functions"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "14"

[build.lifecycle]
  prebuild = "npm install --legacy-peer-deps --force"
